package com.chootdev.railwaydic.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.chootdev.railwaydic.db.StationModel;
import com.chootdev.railwaydic.db.RecentModel;

import com.chootdev.railwaydic.db.StationModelDao;
import com.chootdev.railwaydic.db.RecentModelDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig stationModelDaoConfig;
    private final DaoConfig recentModelDaoConfig;

    private final StationModelDao stationModelDao;
    private final RecentModelDao recentModelDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        stationModelDaoConfig = daoConfigMap.get(StationModelDao.class).clone();
        stationModelDaoConfig.initIdentityScope(type);

        recentModelDaoConfig = daoConfigMap.get(RecentModelDao.class).clone();
        recentModelDaoConfig.initIdentityScope(type);

        stationModelDao = new StationModelDao(stationModelDaoConfig, this);
        recentModelDao = new RecentModelDao(recentModelDaoConfig, this);

        registerDao(StationModel.class, stationModelDao);
        registerDao(RecentModel.class, recentModelDao);
    }
    
    public void clear() {
        stationModelDaoConfig.clearIdentityScope();
        recentModelDaoConfig.clearIdentityScope();
    }

    public StationModelDao getStationModelDao() {
        return stationModelDao;
    }

    public RecentModelDao getRecentModelDao() {
        return recentModelDao;
    }

}
