package com.chootdev.railwaydic.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "STATION_MODEL".
 */
@Entity
public class StationModel {

    @Id(autoincrement = true)
    private Long id;

    @NotNull
    private String station_code;
    private String name;
    private String type;
    private String telephone;
    private String distence_miles;
    private String distence_km;
    private String height_feet;
    private String height_meters;
    private String station_code_no;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public StationModel() {
    }

    public StationModel(Long id) {
        this.id = id;
    }

    @Generated
    public StationModel(Long id, String station_code, String name, String type, String telephone, String distence_miles, String distence_km, String height_feet, String height_meters, String station_code_no) {
        this.id = id;
        this.station_code = station_code;
        this.name = name;
        this.type = type;
        this.telephone = telephone;
        this.distence_miles = distence_miles;
        this.distence_km = distence_km;
        this.height_feet = height_feet;
        this.height_meters = height_meters;
        this.station_code_no = station_code_no;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @NotNull
    public String getStation_code() {
        return station_code;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStation_code(@NotNull String station_code) {
        this.station_code = station_code;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getType() {
        return type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getDistence_miles() {
        return distence_miles;
    }

    public void setDistence_miles(String distence_miles) {
        this.distence_miles = distence_miles;
    }

    public String getDistence_km() {
        return distence_km;
    }

    public void setDistence_km(String distence_km) {
        this.distence_km = distence_km;
    }

    public String getHeight_feet() {
        return height_feet;
    }

    public void setHeight_feet(String height_feet) {
        this.height_feet = height_feet;
    }

    public String getHeight_meters() {
        return height_meters;
    }

    public void setHeight_meters(String height_meters) {
        this.height_meters = height_meters;
    }

    public String getStation_code_no() {
        return station_code_no;
    }

    public void setStation_code_no(String station_code_no) {
        this.station_code_no = station_code_no;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
